import sys
import numpy as np
from plyfile import PlyData
from pathlib import Path

def export_oriented_bedrock(ply_file: Path, output_ts: Path, max_particles: int = 10000, target_size: float = 10.0, flip_y: bool = False):
    print(f"Loading {ply_file}...")
    plydata = PlyData.read(str(ply_file))
    vertex = plydata['vertex']
    
    x, y, z = vertex['x'], vertex['y'], vertex['z']
    
    # 1. Extract Colors
    C0 = 0.28209479177387814
    if 'f_dc_0' in vertex.data.dtype.names:
        r, g, b = 0.5 + vertex['f_dc_0'] * C0, 0.5 + vertex['f_dc_1'] * C0, 0.5 + vertex['f_dc_2'] * C0
    else:
        r, g, b = vertex['red'] / 255.0, vertex['green'] / 255.0, vertex['blue'] / 255.0
    r, g, b = np.clip(r, 0, 1), np.clip(g, 0, 1), np.clip(b, 0, 1)
    
    # 2. Extract Opacity & Downsample
    opacity = 1 / (1 + np.exp(-vertex['opacity'])) if 'opacity' in vertex.data.dtype.names else np.ones_like(x)
    indices = np.argsort(opacity)[::-1][:max_particles] if len(x) > max_particles else np.arange(len(x))
    
    # 3. Extract Scales and Quaternions
    sx, sy, sz = np.exp(vertex['scale_0']), np.exp(vertex['scale_1']), np.exp(vertex['scale_2'])
    rw, rx, ry, rz = vertex['rot_0'], vertex['rot_1'], vertex['rot_2'], vertex['rot_3']
    norms = np.sqrt(rw**2 + rx**2 + ry**2 + rz**2)
    rw, rx, ry, rz = rw/norms, rx/norms, ry/norms, rz/norms
    
    # 4. Normalization Bounds
    min_x, max_x = np.percentile(x[indices], 2), np.percentile(x[indices], 98)
    min_y, max_y = np.percentile(y[indices], 2), np.percentile(y[indices], 98)
    min_z, max_z = np.percentile(z[indices], 2), np.percentile(z[indices], 98)
    scale_factor = target_size / max(max_x - min_x or 1, max_y - min_y or 1, max_z - min_z or 1)
    cx, cy, cz = (min_x + max_x) / 2, (min_y + max_y) / 2, (min_z + max_z) / 2
    
    print(f"Baking {len(indices)} oriented splats into TypeScript (Double-sided)...")
    with open(output_ts, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by splat2mc\nexport const splatData: number[][] = [\n")
        
        for i in indices:
            px, py, pz = (x[i] - cx) * scale_factor, (y[i] - cy) * scale_factor, (z[i] - cz) * scale_factor
            
            w, i_x, i_y, i_z = rw[i], rx[i], ry[i], rz[i]
            R = np.array([
                [1 - 2*(i_y**2 + i_z**2), 2*(i_x*i_y - w*i_z),     2*(i_x*i_z + w*i_y)],
                [2*(i_x*i_y + w*i_z),     1 - 2*(i_x**2 + i_z**2), 2*(i_y*i_z - w*i_x)],
                [2*(i_x*i_z - w*i_y),     2*(i_y*i_z + w*i_x),     1 - 2*(i_x**2 + i_y**2)]
            ])
            
            scales = np.array([sx[i], sy[i], sz[i]]) * scale_factor
            min_idx = np.argmin(scales)
            nx, ny, nz = R[:, min_idx]
            
            axes = [0, 1, 2]
            axes.remove(min_idx)
            size_x, size_y = scales[axes[0]], scales[axes[1]]
            
            world_y = np.array([0.0, 1.0, 0.0])
            br = np.array([1.0, 0.0, 0.0]) if abs(ny) > 0.999 else (lambda cr: cr / np.linalg.norm(cr))(np.cross(world_y, [nx, ny, nz]))
            ar = R[:, axes[0]]
            roll = np.degrees(np.arctan2(np.dot(np.cross(br, ar), [nx, ny, nz]), np.dot(br, ar)))
            
            if flip_y:
                py, ny, roll = -py, -ny, -roll
                
            f.write(f"  [{px:.3f}, {py:.3f}, {pz:.3f}, {r[i]:.3f}, {g[i]:.3f}, {b[i]:.3f}, {size_x:.3f}, {size_y:.3f}, {nx:.3f}, {ny:.3f}, {nz:.3f}, {roll:.3f}, {opacity[i]:.3f}],\n")
            
        f.write("];\n")
    print(f"✓ Saved to {output_ts}")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Export oriented 3DGS to Bedrock.")
    parser.add_argument("ply_file", type=Path, help="Input .ply file")
    parser.add_argument("-n", "--max-particles", type=int, default=10000, help="Max base particles (outputs 2x this amount)")
    args = parser.parse_args()
    
    export_oriented_bedrock(args.ply_file, Path("SplatData.js"), max_particles=args.max_particles, flip_y=True)